config/routes.rb
Ezslp3::Application.routes.draw do
  root :to => "static_pages#about"
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match   'visits/search_visits_by_date'  => 'visits#search_visits_by_date'
  match   'visits/search_visits_by_patient_authorization'  => 'visits#search_visits_by_patient_authorization'
  resources :visits
  resources :searchs
  resources :patient_authorizations do
    resources :visits
  end
  match   'patients/search'  => 'patients#search'
  resources :patients
  devise_for :users
  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :token_authentications, :only => [:create, :destroy]
  resources :user, :controller => "user"
  resources :dashboard

  match   'about'  => 'static_pages#about'
  match   'contact'  => 'static_pages#contact'
  match   'login'  => 'static_pages#login'
  match   'register'  => 'static_pages#register'
  match   'screencasts'  => 'static_pages#screencasts'
  match   'home'  => 'static_pages#home'
  match   'help'  => 'static_pages#help'
  match   'slp-app-integration'  => 'static_pages#slp-app-integration'

  match '*path', :controller => 'static_pages', :action => 'invalid_route'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :patient_authorization
  has_one :patient, :through => :patient_authorization

  attr_accessible :visit_date, :patient_authorization_id, :visit_notes, :session_length, :therapist_name

#this scope will return only the visits associated with an active patient_authorization. I'm using this in the
#visits controller/index so we only display 'active' visits or a way to 'archive' visits
  scope :active_visits, :joins => :patient_authorization, :conditions => {"patient_authorizations.active" => true}

  def self.get_visits(current_user)
    if current_user.role == 'admin'
      Visit.find_all_by_patient_authorization_id(PatientAuthorization.find_all_by_patient_id(current_user.organization.patients))
    elsif current_user.role == 'super'
      Visit.all
    else
      Visit.find_all_by_patient_authorization_id(PatientAuthorization.find_all_by_patient_id((current_user.patients)))
    end
  end

  def self.search(from_date, to_date, current_user)
    current_user_visits = get_visits(current_user)
    Visit.find_all_by_id(current_user_visits, :conditions => [ "(visit_date  BETWEEN ? AND ?)", from_date, to_date])
  end

  validates :visit_date, :presence => true
  validates :visit_notes, :presence => true
  validate :validate_visit_date #this verifies a visit date is between the to and from dates of a patient authorization
  private
    def validate_visit_date
      self.errors.add(:visit_date, " is not within range for the active patient authorization. The
      current authorization dates for this patient are #{self.patient_authorization.from_date} to #{self.patient_authorization.to_date}") unless
      ((self.patient_authorization.from_date)..(self.patient_authorization.to_date)).include?(self.visit_date)
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
require 'will_paginate/array'
  before_filter :patients_for_collection_select, :only => [:new, :create, :edit]

#this index method is crazy code. It supports the visits link on the patient_authorizations index view, but we also need to
#ensure a user is authorized to view patient_authorizations/:id/visits. first if statement checks to see if route like 
#patient_authorizations/3/visits has been clicked. 2nd if statement then verifies the user has the right to view those visits,
#if they do then we display them, if not we flash "Unauthorized Page View"
  def index
    if params[:patient_authorization_id] #this makes the Vists link active; if this is false we drop down to line 14
      if @patient_authorization = PatientAuthorization.get_authorizations(current_user).select {|p| p.id.eql?(params[:patient_authorization_id].to_i) }.first #this checkes whether the user has access to the this visit ID
      @patient_authorization = PatientAuthorization.find(params[:patient_authorization_id])
      @patient_authorizations = PatientAuthorization.get_authorizations(current_user)
      @visits = @patient_authorization.visits.paginate(:page => params[:page], :per_page => 10)
      else
        flash[:notice] = "Unauthorized Page View"
        redirect_to visits_url
      end
    else
      @visits = Visit.active_visits.get_visits(current_user).paginate(:page => params[:page], :per_page => 10)
    end
  end

  def show
    if @visit = Visit.get_visits(current_user).select {|p| p.id.eql?(params[:id].to_i) }.first
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @patient }
      end
    else
      flash[:notice] = "Unauthorized Page View"
      redirect_to visits_url
    end
  end

  def new
    @visit = if params[:patient_id].blank?
      @visit = Visit.new
    else
      patient = Patient.find params[:patient_id]
      patient_authorization = PatientAuthorization.find_by_patient_id(patient.id, :conditions => {:active => true})
      patient_authorization.visits.build
    end
   end

  def create
    @visit = Visit.new(params[:visit])
#add therapist_name in case a patient is assigned a new therapist, then the therapist that performs a visit does not change
    @visit.therapist_name = @visit.patient_authorization.patient.user.email
    if @visit.save
      #TODO when we edit a visit we need to also update it in the calendar
      #here we create and save an 'event' for the calendar
      @event = Event.new :name => @visit.patient_authorization.patient.patient_full_name, :start_at => @visit.visit_date,
                         :end_at => @visit.visit_date, :visit_id => @visit.id, :organization_id => current_user.organization.id
      @event.save
      redirect_to @visit, :notice => "Successfully created visit."
    else
      render :action => 'new'
    end
  end

  def edit
      #TODO when we edit a visit we need to also update it in the calendar
      if @visit = Visit.get_visits(current_user).select {|p| p.id.eql?(params[:id].to_i) }.first
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @patient }
      end
    else
      flash[:notice] = "Unauthorized Page View"
      redirect_to visits_url
    end
  end

  def update
    @visit = Visit.find(params[:id])
    if @visit.update_attributes(params[:visit])
      redirect_to @visit, :notice  => "Successfully updated visit."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @visit = Visit.find(params[:id])
    @event = Event.find_by_visit_id(params[:id]) #we also destroy the calendar event if we destroy the visit
    @visit.destroy
    @event.destroy
    redirect_to visits_url, :notice => "Successfully destroyed visit."
  end

  def patients_for_collection_select
    patient_ids = Patient.get_patients(current_user)
    @patients = PatientAuthorization.find(:all, :conditions => { :active => true, :patient_id => patient_ids })
  end

  def search_visits_by_date
    from_date = Date.new(params[:from_date][:year].to_i, params[:from_date][:month].to_i, params[:from_date][:day].to_i).to_s(:db)
    to_date = Date.new(params[:to_date][:year].to_i, params[:to_date][:month].to_i, params[:to_date][:day].to_i).to_s(:db)
    @visits = Visit.search(from_date, to_date, current_user)
      respond_to do |format|
        format.html
        format.pdf do
          pdf = VisitPdf.new(@visits, from_date, to_date)
          send_data pdf.render
        end
      end
   end

  def search_visits_by_patient_authorization
    @visits = Visit.find_all_by_patient_authorization_id(params[:patient_authorization][:patient_authorization_id])
    respond_to do |format|
      format.html
      format.pdf do
          pdf = VisitByAuthPdf.new(@visits)
          send_data pdf.render
        end
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for @visit do |f| %>
  <%= f.error_messages %>
</p>
    <%= f.label :patient %><br />
    <%=#only display patients that have active authorizations and are associated to the current user
      collection_select(:visit, :patient_authorization_id, @patients, :id, :name_with_visits)
     %>
  </p>
  <p>
    <%= f.label 'Visit Date (click to enter)' %><br />
    <%= f.text_field :visit_date, :size => 10 %>
  </p>
  <p>
    <%= f.label 'Session Length(in minutes)' %><br />
    <%= f.text_field :session_length, :size => '3' %>
  </p>
  <p>
    <%= f.label :visit_notes %><br />
    <%= f.text_area :visit_notes, :cols => "60", :rows => "10" %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/visits/edit.html.erb
<% title "Edit Visit" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @visit %> |
  <%= link_to "View All", visits_path %>
</p>

app/views/visits/index.html.erb
<table>
  <tr>
    <th>Visit Date</th>
    <th>Patient</th>
    <th>Therapist</th>
    <th>Session Length</th>
  </tr>
  <% for visit in @visits %>
    <tr>
      <td><%= visit.visit_date %></td>
      <td><%= visit.patient_authorization.patient.patient_full_name %></td>
      <td><%= visit.therapist_name %></td>
      <td><center><%= visit.session_length %></center></td>
      <td><%= link_to "Show", visit, :class => 'btn btn-mini' %></td>
      <td><%= link_to "Edit", edit_visit_path(visit), :class => 'btn btn-mini' %></td>
      <td><%= link_to "Destroy", visit, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @visits %>
<p><%= link_to "New Visit", new_visit_path, :class => 'btn btn-primary' %></p><p align="right"><%= link_to 'Search Visits', searchs_path %><br/></p>

app/views/visits/new.html.erb
<% title "New Visit" %>

<%= render 'form' %>

<p><%= link_to "Back to List", visits_path %></p>

app/views/visits/search.html.erb
<br/>
Your Search Returned <font color=red><%= @visits.count %></font> Records
<p>
<%= link_to "Print PDF", visits_search_path(params.merge(format: 'pdf')) %>
</p>
<% for visit in @visits %>
<div id='visit'>
  <strong>Visit Date:</strong>
  <%= visit.visit_date %><br/>
  <strong>User:</strong>
  <%= visit.patient_authorization.patient.user.email %><br/>
  <strong>Patient Authorization:</strong>
  <%= visit.patient_authorization.patient.patient_full_name %><br/>
  <strong>Visit Notes:</strong>
  <%= visit.visit_notes %><br/><br/>
  <strong>Speech Pathologist:</strong>
  <%= 'Speech Pathologist ______________________________' %><br/>
  <strong>SLP Assistant:</strong>
  <%= 'SLP Assistant  _______________________________________' %><br/><br/><br/><br/>
</div>
<% end %>

app/views/visits/search_visits_by_date.html.erb
Your search returned <font color='red'><%= @visits.count  %></font> visits
<div id='pdf_link'>
  <p><%= link_to "Print PDF", visits_search_visits_by_date_path(params.merge(format: 'pdf')) %></p>
</div>
<% for visit in @visits %>
<div id='visit'>
  <strong>Visit Date:</strong>
  <%= visit.visit_date %><br/>
  <strong>User:</strong>
  <%= visit.patient_authorization.patient.user.email %><br/>
  <strong>Patient Authorization:</strong>
  <%= visit.patient_authorization.patient.patient_full_name %><br/>
  <strong>Visit Notes:</strong>
  <%= visit.visit_notes %><br/><br/>
  <strong>Speech Pathologist:</strong>
  <%= 'Speech Pathologist ______________________________' %><br/>
  <strong>SLP Assistant:</strong>
  <%= 'SLP Assistant  _______________________________________' %><br/><br/><br/><br/>
</div>
<% end %>

app/views/visits/search_visits_by_patient_authorization.html.erb
Your search returned <font color='red'><%= @visits.count  %></font> visits
<div id='pdf_link'>
  <p><%= link_to "Print PDF", visits_search_visits_by_patient_authorization_path(params.merge(format: 'pdf')) %></p>
</div>
<% for visit in @visits %>
<div id='visit'>
  <strong>Visit Date:</strong>
  <%= visit.visit_date %><br/>
  <strong>User:</strong>
  <%= visit.patient_authorization.patient.user.email %><br/>
  <strong>Patient:</strong>
  <%= visit.patient_authorization.patient.patient_full_name %><br/>
  <strong>Visit Notes:</strong>
  <%= visit.visit_notes %><br/><br/>
  <strong>Speech Pathologist:</strong>
  <%= 'Speech Pathologist ______________________________' %><br/>
  <strong>SLP Assistant:</strong>
  <%= 'SLP Assistant  _______________________________________' %><br/><br/><br/><br/>
</div>
<% end %>

app/views/visits/show.html.erb
<% title "Visit" %>

<p>
  <strong>Visit Date:</strong>
  <%= @visit.visit_date %>
</p>
<p>
  <strong>Therapist:</strong>
  <%= @visit.therapist_name %>
</p>
<p>
  <strong>Patient:</strong>
  <%= @visit.patient_authorization.patient.patient_full_name %>
</p>
<p>
  <strong>Session Length:</strong>
  <%= @visit.session_length %>
</p>
<p>
  <strong>Visit Notes:</strong>
  <%= @visit.visit_notes %>
</p>

<p>
  <%= link_to "Edit", edit_visit_path(@visit) %> |
  <%= link_to "Destroy", @visit, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", visits_path %>
</p>