config/routes.rb
Ezslp3::Application.routes.draw do
  root :to => "static_pages#about"
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match   'visits/search_visits_by_date'  => 'visits#search_visits_by_date'
  match   'visits/search_visits_by_patient_authorization'  => 'visits#search_visits_by_patient_authorization'
  resources :visits
  resources :searchs
  resources :patient_authorizations do
    resources :visits
  end
  match   'patients/search'  => 'patients#search'
  resources :patients
  devise_for :users
  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :token_authentications, :only => [:create, :destroy]
  resources :user, :controller => "user"
  resources :dashboard

  match   'about'  => 'static_pages#about'
  match   'contact'  => 'static_pages#contact'
  match   'login'  => 'static_pages#login'
  match   'register'  => 'static_pages#register'
  match   'screencasts'  => 'static_pages#screencasts'
  match   'home'  => 'static_pages#home'
  match   'help'  => 'static_pages#help'
  match   'slp-app-integration'  => 'static_pages#slp-app-integration'

  match '*path', :controller => 'static_pages', :action => 'invalid_route'

end

app/models/patient_authorization.rb
class PatientAuthorization < ActiveRecord::Base
  belongs_to :patient
  has_many :visits
  attr_accessible :to_date, :from_date, :patient_id, :initial_number_visits, :active, :short_term_goals,
                  :long_term_goals, :frequency_per_week, :session_length, :severity_level, :diagnosis
  delegate :patient_full_name, :to => :patient

  def current_number_visits
    self.initial_number_visits - visits.count
  end

  def name_with_visits
    "#{patient.first_name} #{patient.last_name} has #{current_number_visits} visits remaining"
  end

  def name_with_dates
    "#{patient.first_name} #{patient.last_name} #{self.from_date} to #{self.to_date}"
  end

  def self.get_authorizations(current_user)
    if current_user.role == 'admin'
      PatientAuthorization.find_all_by_patient_id(current_user.organization.patients)
    elsif current_user.role == 'super'
      PatientAuthorization.all
    else
      current_user.patient_authorizations
    end
  end

  validates_uniqueness_of :active, :scope => :patient_id, :message => ': Patient currently has an active authorization.'
  validates :initial_number_visits, :presence => true
  validates_numericality_of :initial_number_visits, :greater_than => 0
  validates :from_date, :presence => true
  validates :to_date, :presence => true
 #this verifies the from/to dates are correctly ordered and at least one day on length
  validate :validate_dates, :if => :to_date?, :if => :from_date
  private
    def validate_dates
      self.errors.add(:to_date, " must be after the from date, and must be at least one day in length") unless
      (self.from_date-self.to_date) < 0
  end
end

app/controllers/patient_authorizations_controller.rb
class PatientAuthorizationsController < ApplicationController
  def index
    @patient_authorizations = PatientAuthorization.get_authorizations(current_user)
  end

  def show
    if @patient_authorization = PatientAuthorization.get_authorizations(current_user).select {|p| p.id.eql?(params[:id].to_i) }.first
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @patient }
      end
    else
      flash[:notice] = "Unauthorized Page View"
      redirect_to patient_authorizations_url
    end
  end

  def new
    @patient_authorization = PatientAuthorization.new
#TODO need to add logic to filter patients. we only should display patients in 're-authorize' that are 'eligible'
  end

  def create
    @patient_authorization = PatientAuthorization.new(params[:patient_authorization])
    if @patient_authorization.save
      redirect_to @patient_authorization, :notice => "Successfully created patient authorization."
    else
      render :action => 'new'
    end
  end

  def edit
    if @patient_authorization = PatientAuthorization.get_authorizations(current_user).select {|p| p.id.eql?(params[:id].to_i) }.first
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @patient }
      end
    else
      flash[:notice] = "Unauthorized Page View"
      redirect_to patient_authorizations_url
    end
  end

  def update
    @patient_authorization = PatientAuthorization.find(params[:id])
    if @patient_authorization.update_attributes(params[:patient_authorization])
      redirect_to @patient_authorization, :notice  => "Successfully updated patient authorization."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @patient_authorization = PatientAuthorization.find(params[:id])
    if PatientAuthorization.get_authorizations(current_user).select {|p| p.id.eql?(params[:id].to_i) }.first and
      @patient_authorization.visits.empty? #check if there are any Visits with this Patient Authorization before deleting
      @patient_authorization.destroy
      redirect_to patient_authorizations_url, :notice => "Successfully destroyed patient authorization."
    else
      redirect_to patient_authorizations_url, :notice  => 'This Patient Authorization is a associated with one or more visits. It cannot be destroyed. If you want to remove this authorization you will need to first destroy all visits associated with it.'
    end
  end
end

app/helpers/patient_authorizations_helper.rb
module PatientAuthorizationsHelper
end

app/views/patient_authorizations/_form.html.erb
<%= form_for @patient_authorization do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label 'Patient' %><br />
    <% @patients = Patient.get_patients(current_user).sort! {|a,b| a.last_name <=> b.last_name} %>
    <%= collection_select(:patient_authorization, :patient_id, @patients, :id, :patient_full_name) %>
  </p>

    <%= 'Authorization/Contract Period(click to choose date)' %>
    <a id="pat_auth_help_1" class="slick-toggle" data-id="334" href="#"><img src="/assets/help.png"></a><br/>
    <div id="pat_auth_help_2" class="slickbox" data-id="334" style="display: block;">
      The Authorization or Contract Period is the dates in which you will perform visits for a patient. An initial Patient Authorization is created when a new patient is created. After a patients initial visits have been exhausted a patient will need to be re-authorized to perform additional visits. This is a logical way for you to manage patient contracts or Medicare Authorization.<br/>
    </div>
    <%= f.text_field :from_date, :size => 10 %>
    <%= 'To' %>
    <%= f.text_field :to_date, :size => 10 %><br/><br/>
    <%= 'Number of Visits for this Authorization Period' %><br/>
    <%= f.text_field :initial_number_visits, :size => 2 %><br/><br/>
    <b><%= 'To add a Plan Of Care' %></b>
    <a id="dropdown_1" class="slick-toggle" data-id="335" href="#">Click Here<img src="/assets/dropdown.jpg"></a><br/>
    <div id="dropdown_2" class="slickbox" data-id="335" style="display: block;">
    <%= 'Short Term Goals' %><br/>
    <%= f.text_area :short_term_goals, :cols => "160", :rows => "10" %><br/>
    <%= 'Long Term Goals' %><br/>
    <%= f.text_area :long_term_goals, :cols => "60", :rows => "10" %><br/>
    <%= 'Number of Visits per Week (Frequency)' %><br/>
    <%= f.text_field :frequency_per_week %><br/>
    <%= 'Session Length' %><br/>
    <%= f.text_field :session_length %><br/>
    <%= 'Severity Level' %>
    <%= f.select :severity_level, options_for_select(['Mild', 'Moderate', 'Severe']) %><br/>
    <%= 'Diagnosis' %>
    <%= f.select :diagnosis, options_for_select(['Articulation', 'Fluency', 'Receptive Language',
																								'Expresive Language', 'Mixed Receptive/Expressive Language',
																								'Feeding/Swallowing']) %>
    </div>
    <p><%= f.submit %></p>
<% end %>

app/views/patient_authorizations/edit.html.erb
<% title "Edit Patient Authorization" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @patient_authorization %> |
  <%= link_to "View All", patient_authorizations_path %>
</p>

app/views/patient_authorizations/index.html.erb
<table>
  <tr>
    <th>From Date</th>
    <th>To Date</th>
    <th>Patient</th>
    <th>Therapist</th>
    <th>Initial Number<br/>
        of Visits</th>
    <th>Current Number<br/>
        of Visits Remaining</th>
  </tr>
  <% for patient_authorization in @patient_authorizations %>
    <tr>
      <td><%= patient_authorization.from_date %></td>
      <td><%= patient_authorization.to_date %></td>
      <td><%= patient_authorization.patient.patient_full_name %></td>
      <td><%= patient_authorization.patient.user.email %></td>
      <td><center><%= patient_authorization.initial_number_visits %></center></td>
      <td><center><%=h patient_authorization.current_number_visits %></center></td>
      <td><%= if current_user.admin? then link_to "Show", patient_authorization, :class => 'btn btn-mini'  end %></td>
      <td><%= if current_user.admin? then link_to "Edit", edit_patient_authorization_path(patient_authorization), :class => 'btn btn-mini'  end %></td>
      <td><%= if current_user.admin? then link_to "Destroy", patient_authorization,
                  :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' end %></td>
      <td><%= link_to 'Visits', patient_authorization_visits_path(patient_authorization), :class => 'btn btn-mini' %></td>
    </tr>
  <% end %>
</table>

<p><%= if current_user.admin? then link_to "Re-Authorize a Patient", new_patient_authorization_path, :class => 'btn btn-primary' end %></p>

app/views/patient_authorizations/new.html.erb
<% title "New Patient Authorization" %>

<%= render 'form' %>

<p><%= link_to "Back to List", patient_authorizations_path %></p>

app/views/patient_authorizations/show.html.erb
<% title "Patient Authorization" %>

<p>
  <strong>To Date:</strong>
  <%= @patient_authorization.to_date %>
</p>
<p>
  <strong>From Date:</strong>
  <%= @patient_authorization.from_date %>
</p>
<p>
  <strong>Patient:</strong>
  <%= @patient_authorization.patient.patient_full_name %>
</p>
<p>
  <strong>Initial Number Visits:</strong>
  <%= @patient_authorization.initial_number_visits %>
</p>
<p>
  <strong>Active Status:</strong>
  <%= @patient_authorization.active %>
</p>
<b>Plan of Care</b>
<div style="width:300px;height:220px;border:1px solid black;">
<p>
  <b>Short term goals:</b>
  <%=h @patient_authorization.short_term_goals %>
</p>
<p>
  <b>Long term goals:</b>
  <%=h @patient_authorization.long_term_goals %>
</p>
<p>
  <b>Number of Visits per Week (Frequency):</b>
  <%=h @patient_authorization.frequency_per_week %>
</p>
<p>
  <b>Session Length:</b>
  <%=h @patient_authorization.session_length %>
</p>
<p>
  <b>Severity Level:</b>
  <%=h @patient_authorization.severity_level %>
</p>
<p>
  <b>Diagnosis:</b>
  <%=h @patient_authorization.diagnosis %>
</p>
</div>

<p>
  <%= link_to "Edit", edit_patient_authorization_path(@patient_authorization) %> |
  <%= link_to "Destroy", @patient_authorization, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", patient_authorizations_path %>
</p>