config/routes.rb
Ezslp3::Application.routes.draw do
  root :to => "static_pages#about"
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match   'visits/search_visits_by_date'  => 'visits#search_visits_by_date'
  match   'visits/search_visits_by_patient_authorization'  => 'visits#search_visits_by_patient_authorization'
  resources :visits
  resources :searchs
  resources :patient_authorizations do
    resources :visits
  end
  match   'patients/search'  => 'patients#search'
  resources :patients
  devise_for :users
  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :token_authentications, :only => [:create, :destroy]
  resources :user, :controller => "user"
  resources :dashboard

  match   'about'  => 'static_pages#about'
  match   'contact'  => 'static_pages#contact'
  match   'login'  => 'static_pages#login'
  match   'register'  => 'static_pages#register'
  match   'screencasts'  => 'static_pages#screencasts'
  match   'home'  => 'static_pages#home'
  match   'help'  => 'static_pages#help'
  match   'slp-app-integration'  => 'static_pages#slp-app-integration'

  match '*path', :controller => 'static_pages', :action => 'invalid_route'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
  has_many :patient_authorizations
  accepts_nested_attributes_for :patient_authorizations
  has_one :current_authorization, :class_name => 'PatientAuthorization',
                                  :conditions => { :active => true }


  attr_accessible :first_name, :last_name, :middle_name, :address_1, :address_2, :city, :state, :zip, :phone, :dob, :medicaid_number, :contact, :user_id, :patient_authorizations_attributes

  def patient_full_name
    "#{first_name} #{last_name}"
  end

#In this method we find all patient authorizations for the patient that are active, and return the current_number_visits
#Or if there are not active patient authorizations, then we return 'No active authorizations'
  def show_remaining_visits(patient)
    @pat_auth = PatientAuthorization.find_by_patient_id(patient, :conditions => {:active => true})
    if @pat_auth != nil
      @pat_auth.current_number_visits
    else
      'No Active Authorizations'
    end
  end


 #Calling this from the controller for multi-tenancy
  def self.get_patients(current_user)
    if current_user.role == 'admin'
      current_user.organization.patients
    elsif current_user.role == 'super'
      Patient.all
    else
      current_user.patients
    end
  end

  def self.search(search_param, current_user)
    search_condition = "%" + search_param.downcase + "%"
    current_user_patients = get_patients(current_user)
    find_all_by_id(current_user_patients, :conditions => ['lower(first_name) LIKE ? OR lower(last_name) LIKE ?', search_condition, search_condition])
  end

  validates :first_name, :presence => true
  validates :last_name, :presence => true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :get_users_for_collection_select

  def index
    @patients = Patient.get_patients(current_user) #multi-tenancy; only returns tasks with the the current users org
    @patients.sort! { |a,b| a.last_name.downcase <=> b.last_name.downcase }
  end

#if conditionals below only allows user to view model if it is returned via the get_patients method
 def show
    if @patient = Patient.get_patients(current_user).select {|p| p.id.eql?(params[:id].to_i) }.first
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @patient }
      end
    else
      flash[:notice] = "Unauthorized Page View"
      redirect_to patients_url
    end
  end

  def new
    @patient = Patient.new
    @patient.patient_authorizations.build
  end

  def create
    @patient = Patient.new(params[:patient])
    if @patient.save
      redirect_to patients_path, :notice => "Successfully created patient."
    else
      render :action => 'new'
    end
  end

  def edit
    if @patient = Patient.get_patients(current_user).select {|p| p.id.eql?(params[:id].to_i) }.first
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @patient }
      end
    else
      flash[:notice] = "Unauthorized Page View"
      redirect_to patients_url
    end
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update_attributes(params[:patient])
      redirect_to @patient, :notice  => "Successfully updated patient."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    if Patient.get_patients(current_user).select {|p| p.id.eql?(params[:id].to_i) }.first and @patient.patient_authorizations.empty?
      @patient.destroy
      redirect_to patients_url, :notice => "Successfully destroyed patient."
    else
      redirect_to patients_url, :notice  => 'This patient is associated with a Patient Authorization. It cannot be destroyed. If you want to remove this patient you will need to destroy the Patient Authorization and any associated visits.'
    end
  end

#TODO this should only return all users for admin role
  def get_users_for_collection_select
    @users = User.find_all_by_organization_id(current_user.organization, :order => :email)
  end

  def search
    @patients = Patient.search(params[:search], current_user)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for @patient do |f| %>
  <%= f.error_messages %>
<table>
<tr>
<th><%= f.label :first_name %></th>
<th><%= f.label :middle_name %></th>
<th><%= f.label :last_name%></th>
</tr>
<tr>
<td><%= f.text_field :first_name, :size => 20 %></td>
<td><%= f.text_field :middle_name, :size => 20%></td>
<td><%= f.text_field :last_name, :size => 20%></td>
</tr>
</table>
<table>
<tr>
    <th><%= f.label :address_1 %></th>
   <th> <%= f.label :address_2 %></th>
</tr>
<tr>
   <td> <%= f.text_field :address_1 %></td>
   <td> <%= f.text_field :address_2 %></td>
<tr>
</table>
<table>
<tr>
<th><%= f.label :city%></th>
<th><%= f.label :state%></th>
<th><%= f.label :zip%></th>
<th><%= f.label :phone%></th>
</tr>
<tr>
<td><%= f.text_field :city, :size => 20 %></td>
<td><%= f.text_field :state, :size => 2%></td>
<td><%= f.text_field :zip, :size => 6%></td>
<td><%= f.text_field :phone, :size => 9%></td>
</tr>
</table>
  <p>
    <%= 'Date of Birth'  %>
    <%= f.date_select :dob, :start_year => 1930, :order => [:month, :day, :year]%><br/><br/>
    <%= f.label :contact%>
    <%= f.text_field :contact%><br/>
    <%= f.label :medicaid_number%>
    <%= f.text_field :medicaid_number%>
  </p>
  <%= f.fields_for :patient_authorizations do |pat_auth| %>
    <%= 'Authorization/Contract Period(click to choose date)' %>
    <a id="pat_auth_help_1" class="slick-toggle" data-id="334" href="#"><img src="/assets/help.png"></a><br/>
    <div id="pat_auth_help_2" class="slickbox" data-id="334" style="display: block;">
      The Authorization or Contract Period is the dates in which you will perform visits for a patient. An initial Patient Authorization is created when a new patient is created. After a patients initial visits have been exhausted a patient will need to be re-authorized to perform additional visits. This is a logical way for you to manage patient contracts or Medicare Authorization.<br/>
    </div>
    <%= pat_auth.text_field :from_date, :size => 10 %>
    <%= 'To' %>
    <%= pat_auth.text_field :to_date, :size => 10 %><br/><br/>
    <%= 'Number of Visits for this Authorization Period' %><br/>
    <%= pat_auth.text_field :initial_number_visits, :size => 2 %><br/><br/>
    <b><%= 'To add a Plan Of Care' %></b>
    <a id="dropdown_1" class="slick-toggle" data-id="335" href="#">Click Here<img src="/assets/dropdown.jpg"></a><br/>
    <div id="dropdown_2" class="slickbox" data-id="335" style="display: block;">
			<%= 'Short Term Goals' %><br/>
			<%= pat_auth.text_area :short_term_goals, :cols => "60", :rows => "10" %><br/>
			<%= 'Long Term Goals' %><br/>
			<%= pat_auth.text_area :long_term_goals, :cols => "60", :rows => "10" %><br/>
			<%= 'Number of Visits per Week (Frequency)' %><br/>
			<%= pat_auth.text_field :frequency_per_week %><br/>
			<%= 'Session Length' %><br/>
			<%= pat_auth.text_field :session_length %><br/>
			<%= 'Severity Level' %>
			<%= pat_auth.select :severity_level, options_for_select(['Mild', 'Moderate', 'Severe']) %><br/>
			<%= 'Diagnosis' %>
			<%= pat_auth.select :diagnosis, options_for_select(['Articulation', 'Fluency', 'Receptive Language', 'Expresive Language']) %>
    </div>
  <% end %>
  <p>
    <%= f.label :user %>
    <a id="user_help_1" class="slick-toggle" data-id="336" href="#"><img src="/assets/help.png"></a><br/>
    <div id="user_help_2" class="slickbox" data-id="336" style="display: block;">
      Assign a user to a patient. This user will be able to create visits for this patient. Remember an Admin user can create visits for all patients. A user with the Therapist role can only create visits for patients assigned to them.
    </div>

    <%=
        collection_select(:patient, :user_id, @users, :id, :email)
    %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/patients/edit.html.erb
<% title "Edit Patient" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @patient %> |
  <%= link_to "View All", patients_path %>
</p>

app/views/patients/index.html.erb
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Therapist</th>
    <th>Remaining Visits</th>
  </tr>
  <% for patient in @patients %>
    <tr>
      <td><%= patient.first_name %></td>
      <td><%= patient.last_name %></td>
      <td><%= patient.user.email %></td>
      <td><center><%=h patient.show_remaining_visits(patient) %></center></td>
      <td><%= link_to "Show", patient, :class => 'btn btn-mini'  %></td>
      <td><%= if current_user.admin? then link_to "Edit", edit_patient_path(patient), :class => 'btn btn-mini'  end %></td>
      <td><%= if current_user.admin?  then link_to "Destroy", patient, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' end %></td>
    </tr>
  <% end %>
</table>
<%= if current_user.admin? then link_to 'New Patient', new_patient_path, :class => 'btn btn-primary' end %><p/>

app/views/patients/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", patients_path %></p>

app/views/patients/search.html.erb
 <ul>
    <% if @patients.empty?  %>
      No patients found with that first or last name!
    <% else  %>
Your search returned <font color='red'><%= @patients.count  %></font> patients
    <% @patients.each do |patient| %>
      <li><%= link_to patient.patient_full_name,
      :action => 'show', :id => patient.id  %></li>
  <% end %>
  <% end %>
 </ul>

app/views/patients/show.html.erb
<% title "Patient" %>

<p>
  <strong>First Name:</strong>
  <%= @patient.first_name %>
</p>
<p>
  <strong>Middle Name:</strong>
  <%= @patient.middle_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @patient.last_name %>
</p>
<p>
  <strong>Address 1:</strong>
  <%= @patient.address_1 %>
</p>
<p>
  <strong>Address 2:</strong>
  <%= @patient.address_2 %>
</p>
<p>
  <strong>City:</strong>
  <%= @patient.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @patient.state %>
</p>
<p>
  <strong>Zip:</strong>
  <%= @patient.zip %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>
<p>
  <strong>Therapist:</strong>
  <%= @patient.user.email %>
</p>

<p>
  <%= link_to "Edit", edit_patient_path(@patient) %> |
  <%= link_to "Back", patients_path %> |
  <% if @patient.show_remaining_visits(@patient) != 'No Active Authorizations' then %>
  <%= link_to 'New Visit', new_visit_path({:patient_id => @patient}) %>
  <% else %>
  <%= 'No Active Authorizations' %>
  <% end %>
</p>