config/routes.rb
Ezslp3::Application.routes.draw do
  root :to => "static_pages#about"
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match   'visits/search_visits_by_date'  => 'visits#search_visits_by_date'
  match   'visits/search_visits_by_patient_authorization'  => 'visits#search_visits_by_patient_authorization'
  resources :visits
  resources :searchs
  resources :patient_authorizations do
    resources :visits
  end
  match   'patients/search'  => 'patients#search'
  resources :patients
  devise_for :users
  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :token_authentications, :only => [:create, :destroy]
  resources :user, :controller => "user"
  resources :dashboard

  match   'about'  => 'static_pages#about'
  match   'contact'  => 'static_pages#contact'
  match   'login'  => 'static_pages#login'
  match   'register'  => 'static_pages#register'
  match   'screencasts'  => 'static_pages#screencasts'
  match   'home'  => 'static_pages#home'
  match   'help'  => 'static_pages#help'
  match   'slp-app-integration'  => 'static_pages#slp-app-integration'

  match '*path', :controller => 'static_pages', :action => 'invalid_route'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "EzSLP" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js' %>
    <%= csrf_meta_tag %>
    <%= analytics_init if Rails.env.production? %>
    <%= yield(:head) %>
  </head>
<% if user_signed_in? %>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/home">ezSLP</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/home">Home</a></li>
              <li><a href="/visits">Visits</a></li>
              <li><a href="/patients">Patients</a></li>
              <li><a href="/patient_authorizations">Patient Authorizations</a></li>
							<% if current_user.admin? %>
								<li><a href="/dashboard">Users</a></li>
								<li><a href="/calendar">Calendar</a></li>
							<% end %>
              <li><a href="/help">Help</a></li>
              <li><a href="/users/sign_out">Sign Out</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </div>
  </span>
  <body>
    <div id="container">
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
  <span style="text-align: right">
      <div id="user_nav">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>(<%= current_organization.name %>)
          <%= link_to "Sign out", destroy_user_session_path %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
        <% end %>
      </div>
    </span>
        <% end %>
    <div class="container">
      <div class="main-content">
    <div id='patient_search'>
    <span style="text-align: right">
    <%= form_tag :controller => 'patients', :action => 'search', :method => 'get' do %>
          <%= text_field_tag :search, params[:search], :id => 'search_field' %>
          <%= submit_tag "Search Patients", :name => nil %>
    <% end %>
    </div>
      <%= yield %>
    </div>
<!-- begin olark code --><script type='text/javascript'>/*{literal}<![CDATA[*/window.olark||(function(i){var e=window,h=document,a=e.location.protocol=="https:"?"https:":"http:",g=i.name,b="load";(function(){e[g]=function(){(c.s=c.s||[]).push(arguments)};var c=e[g]._={},f=i.methods.length; while(f--){(function(j){e[g][j]=function(){e[g]("call",j,arguments)}})(i.methods[f])} c.l=i.loader;c.i=arguments.callee;c.f=setTimeout(function(){if(c.f){(new Image).src=a+"//"+c.l.replace(".js",".png")+"&"+escape(e.location.href)}c.f=null},20000);c.p={0:+new Date};c.P=function(j){c.p[j]=new Date-c.p[0]};function d(){c.P(b);e[g](b)}e.addEventListener?e.addEventListener(b,d,false):e.attachEvent("on"+b,d); (function(){function l(j){j="head";return["<",j,"></",j,"><",z,' onl'+'oad="var d=',B,";d.getElementsByTagName('head')[0].",y,"(d.",A,"('script')).",u,"='",a,"//",c.l,"'",'"',"></",z,">"].join("")}var z="body",s=h[z];if(!s){return setTimeout(arguments.callee,100)}c.P(1);var y="appendChild",A="createElement",u="src",r=h[A]("div"),G=r[y](h[A](g)),D=h[A]("iframe"),B="document",C="domain",q;r.style.display="none";s.insertBefore(r,s.firstChild).id=g;D.frameBorder="0";D.id=g+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){D.src="javascript:false"} D.allowTransparency="true";G[y](D);try{D.contentWindow[B].open()}catch(F){i[C]=h[C];q="javascript:var d="+B+".open();d.domain='"+h.domain+"';";D[u]=q+"void(0);"}try{var H=D.contentWindow[B];H.write(l());H.close()}catch(E){D[u]=q+'d.write("'+l().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}c.P(2)})()})()})({loader:(function(a){return "static.olark.com/jsclient/loader0.js?ts="+(a?a[1]:(+new Date))})(document.cookie.match(/olarkld=([0-9]+)/)),name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('7699-235-10-4052');/*]]>{/literal}*/</script>
<!-- end olark code -->
</body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html> 
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Nimbuslike
Description: A two-column, fixed-width design for 1024x768 screen resolutions.
Version    : 1.0
Released   : 20090717

-->
<%= stylesheet_link_tag "bootstrap"%>
<%= stylesheet_link_tag "bootstrap-responsive"%>
<%= stylesheet_link_tag "static_pages" %>
<%= stylesheet_link_tag "jquery-ui.min" %>
<%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js' %>
    <%= csrf_meta_tag %>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>EZslp. SLP Therapy Clinical Managment Software. Soap notes, care plans, and authorization periods</title>
<meta name="keywords" content="slp, speech, clinical, therapy, Soap Notes, Progress notes, Therapy Software, Therapy documentation, Clinic software" />
<meta name="description" content="slp speech Therapy clinic software. Progress notes, care plans. EZslp Visit Tracker is software accessible via the Internet that manages speech therapy clinics. " />
<link href="stylesheets/static_pages.css" rel="stylesheet" type="text/css" media="screen" />
<!--Begin Google Analytics-->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30924466-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<!--End Google Analytics-->
</head>
<body>
    <div id="container-fluid">
        <header>
            <div class="main-header navbar row-fluid">
                <div class="navbar-inner">
                    <a class="brand" href="/about"><%=image_tag("logo.png", alt: "ezSLP logo")%></a>
                    <ul class="nav nav-pills pull-right">
                        <li class="active">
                            <a id="blue-button" href="/register">REGISTER/LOGIN</a>
                        </li>
                        <li><a href=""><%=image_tag("twitter-square.png", alt:"Twitter logo")%></a></li>
                        <li><a href=""><%=image_tag("youtube-square.png", alt:"Youtube logo")%></a></li>
                    </ul>
                </div>
            </div>    
            <nav class="navbar row-fluid main-nav">
                <div class="navbar-inner">       
                    <ul class="nav nav-stacked pull-right main-nav">
                        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "HOME", about_path%></li>
                        <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "CONTACT", contact_path%></li>
                        <li class="<%= 'active' if current_page?(register_path) %>"><%= link_to "REGISTER", register_path%></li>
                        <li class="<%= 'active' if current_page?(screencasts_path) %>"><%= link_to "VIDEOS", screencasts_path%></li>
                    </ul>
                </div>   
            </nav>  
        </header>
        <div class="wrapper">
            <%= yield %>

	    </div><!-- end container-fluid div -->

    </div>           
    <footer>
        <div class="navbar navbar-default navbar-fixed-bottom">
            <div class="container">
                <p class="navbar-text pull-left">2018 - Site Built By Mark Locklear</p>
                <a href="https://www.youtube.com/user/ezslp" class="navbar-btn btn pull-right">
                    <%=image_tag("footeryoutube-square.png", alt:"Youtube logo", size: "45x45")%>
                </a>
                <a href="https://www.youtube.com/user/ezslp" class="navbar-btn btn pull-right">
                    <%=image_tag("footertwitter-square.png", alt:"Twitter logo", size: "45x45")%>
                </a>
                <a href="https://www.youtube.com/user/ezslp" class="navbar-btn btn pull-right">
                    <%=image_tag("footerenvelope.png", alt:"Email envelope logo", size: "60x45")%>
                </a>
            </div>
        </div>
    </footer>
<!-- begin olark code --><script type='text/javascript'>/*{literal}<![CDATA[*/window.olark||(function(i){var e=window,h=document,a=e.location.protocol=="https:"?"https:":"http:",g=i.name,b="load";(function(){e[g]=function(){(c.s=c.s||[]).push(arguments)};var c=e[g]._={},f=i.methods.length; while(f--){(function(j){e[g][j]=function(){e[g]("call",j,arguments)}})(i.methods[f])} c.l=i.loader;c.i=arguments.callee;c.f=setTimeout(function(){if(c.f){(new Image).src=a+"//"+c.l.replace(".js",".png")+"&"+escape(e.location.href)}c.f=null},20000);c.p={0:+new Date};c.P=function(j){c.p[j]=new Date-c.p[0]};function d(){c.P(b);e[g](b)}e.addEventListener?e.addEventListener(b,d,false):e.attachEvent("on"+b,d); (function(){function l(j){j="head";return["<",j,"></",j,"><",z,' onl'+'oad="var d=',B,";d.getElementsByTagName('head')[0].",y,"(d.",A,"('script')).",u,"='",a,"//",c.l,"'",'"',"></",z,">"].join("")}var z="body",s=h[z];if(!s){return setTimeout(arguments.callee,100)}c.P(1);var y="appendChild",A="createElement",u="src",r=h[A]("div"),G=r[y](h[A](g)),D=h[A]("iframe"),B="document",C="domain",q;r.style.display="none";s.insertBefore(r,s.firstChild).id=g;D.frameBorder="0";D.id=g+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){D.src="javascript:false"} D.allowTransparency="true";G[y](D);try{D.contentWindow[B].open()}catch(F){i[C]=h[C];q="javascript:var d="+B+".open();d.domain='"+h.domain+"';";D[u]=q+"void(0);"}try{var H=D.contentWindow[B];H.write(l());H.close()}catch(E){D[u]=q+'d.write("'+l().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}c.P(2)})()})()})({loader:(function(a){return "static.olark.com/jsclient/loader0.js?ts="+(a?a[1]:(+new Date))})(document.cookie.match(/olarkld=([0-9]+)/)),name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('7699-235-10-4052');/*]]>{/literal}*/</script>
<!-- end olark code -->
</body>
</html>